version: "1.0"
services:
  gafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Test1234
