{
 "title": "Dev Portal - Regression result",
 "description": "Dev PortalTest Results Grafana Dashboard",
 "tags": [ "regression-result" ],
 "time": { "from": "2024-06-16T17:00:00.000Z", "to": "2024-06-21T16:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "test_site", "label": "Environment", "query": "SELECT label FROM test_site" },
   {
    "name": "language",
    "label": "Language",
    "query": "SELECT country_code FROM localized"
   }
  ]
 },
 "panels": [
  {
   "title": "Pass & Fail (%)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT\n    (SELECT COUNT(status)\n        FROM test_cases_status\n        JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n        JOIN localized ON test_runs.localized_id = localized.id\n        JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE status = 'PASS' AND country_code = '$language' AND test_site.label = '$test_site' AND $__timeFilter(started_at)\n    ) as PASS,\n    (SELECT COUNT(status)\n        FROM test_cases_status\n        JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n        JOIN localized ON test_runs.localized_id = localized.id\n        JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE status = 'FAIL' AND country_code = '$language' AND test_site.label = '$test_site' AND $__timeFilter(started_at)\n    ) as FAIL,\n    (SELECT COUNT(status)\n        FROM test_cases_status\n        JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n        JOIN localized ON test_runs.localized_id = localized.id\n        JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE status = 'SKIP' AND country_code = '$language' AND test_site.label = '$test_site' AND $__timeFilter(started_at)\n    ) as SKIP"
    }
   ]
  },
  {
   "title": "Pass Rate(%)",
   "type": "gauge",
   "description": "Latest testing Pass rate",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "query": "SELECT (\n        SELECT COUNT(status)\n        FROM\n            test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN localized ON test_runs.localized_id = localized.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            status = 'PASS'\n            AND country_code = '$language'\n            AND test_site.label = '$test_site'\n            AND $__timeFilter(started_at)\n    ) / (\n        SELECT COUNT(status)\n        FROM\n            test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN localized ON test_runs.localized_id = localized.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            country_code = '$language'\n            AND test_site.label = '$test_site'\n            AND $__timeFilter(started_at) \n    ) * 100",
     "rawSql": "SELECT (\n        SELECT COUNT(status)\n        FROM\n            test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN localized ON test_runs.localized_id = localized.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            status = 'PASS'\n            AND country_code = '$language'\n            AND test_site.label = '$test_site'\n            AND $__timeFilter(started_at)\n    ) / (\n        SELECT COUNT(status)\n        FROM\n            test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN localized ON test_runs.localized_id = localized.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            country_code = '$language'\n            AND test_site.label = '$test_site'\n            AND $__timeFilter(started_at) \n    ) * 100 AS pass_rate_percentage\n"
    }
   ]
  },
  {
   "title": "Testing Fail",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT\n    name AS \"Test Cases\",\n    elapsed AS \"Elapsed (s)\",\n    status AS Status,\n    -- CONVERT_TZ(started_at, \"+00:00\", \"+07:00\") AS \"Tested at\"\n    started_at AS \"Tested at\"\nFROM\n    test_cases_status\n    JOIN test_cases ON test_cases_status.test_case_id = test_cases.id\n    JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n    JOIN localized ON test_runs.localized_id = localized.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    status = \"FAIL\"\n    AND label = '$test_site'\n    AND country_code = '$language'\n    AND $__timeFilter(started_at);"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "gauge",
   "description": "Latest automated execution time",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "-- SELECT SUM(elapsed)\n-- FROM\n--     test_cases_status\n--     JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n--     JOIN localized ON test_runs.localized_id = localized.id\n--     JOIN test_site ON test_runs.test_site_id = test_site.id\nSELECT SUM(elapsed)\nFROM\n    -- test_cases_status\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN localized ON test_runs.localized_id = localized.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    country_code = '$language'\n    AND test_site.label = '$test_site'\n    AND $__timeFilter(started_at)"
    }
   ]
  },
  {
   "title": "Avg Pass Rate (%)",
   "type": "gauge",
   "description": "Average total testing PASS rate",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT (\n        SELECT COUNT(status)\n        FROM test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            status = 'PASS'\n            AND test_site.label = '$test_site'\n    ) / (\n        SELECT COUNT(status)\n        FROM test_cases_status\n            JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n            JOIN test_site ON test_runs.test_site_id = test_site.id\n        WHERE\n            test_site.label = '$test_site'\n    ) * 100"
    }
   ]
  },
  {
   "title": "Avg Execution Time",
   "type": "gauge",
   "description": "Total average execution time",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "partner_portal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_results",
     "query": "SELECT AVG(elapsed)\nFROM\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site'\n",
     "rawSql": "SELECT AVG(elapsed)\nFROM\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site'\n",
     "tags": [
      { "key": "project_name", "operator": "=", "value": "RobotTests" }
     ]
    }
   ]
  },
  {
   "title": "Regression (times)",
   "type": "stat",
   "description": "Total Regression (times)",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT COUNT(test_run_status.id)\nFROM\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site';\n"
    }
   ]
  },
  {
   "title": "Total Execution time",
   "type": "stat",
   "description": "Total automated test execution time ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "partner_portal",
     "query": "SELECT SUM(elapsed)\nFROM\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site'",
     "rawSql": "SELECT SUM(elapsed)\nFROM\n    test_run_status\n    JOIN test_runs ON test_run_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site'\n"
    }
   ]
  },
  {
   "title": "Test Execution (times)",
   "type": "stat",
   "description": "Total test cases execution (times)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT COUNT(test_cases_status.id)\nFROM\n    test_cases_status\n    JOIN test_runs ON test_cases_status.test_run_id = test_runs.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    label = '$test_site';"
    }
   ]
  },
  {
   "title": "Testing Result",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "dev_portal",
     "rawSql": "SELECT\n    name as TestSuites,\n    elapsed as \"Elapsed (s)\",\n    passed as PASS,\n    failed as FAIL,\n    status as Status,\n    -- CONVERT_TZ(started_at, \"+00:00\", \"+07:00\") as \"Tested at\"\n    started_at as \"Tested at\"\nFROM suite_status\n    JOIN suites ON suite_status.suite_id = suites.id\n    JOIN test_runs ON suite_status.test_run_id = test_runs.id\n    JOIN localized ON test_runs.localized_id = localized.id\n    JOIN test_site ON test_runs.test_site_id = test_site.id\nWHERE\n    $__timeFilter(started_at)\n    AND country_code = '$language'\n    AND label = '$test_site';"
    }
   ]
  }
 ]
}