name: Running unittest

on:
  pull_request:
    branches:
      - main
    paths:
      - 'DumpDB/**'
      - '.github/**'
      - requirements.txt

jobs:
  running-unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repos
      uses: actions/checkout@v4.1.3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        cache: pip
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install --break-system-packages -r requirements.txt
    - name: actions-setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.32.1
      with:
        root-password: Test1234
        user: test
        password: Test1234
    - name: Create DB
      run: python3 DumpDB/createDB.py
    - name: Run unit-test readJSON.py
      run: python3 DumpDB/readJSON.py
    - name: Run unit-test validateJSON.py
      run: python3 DumpDB/validateJSON.py